require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'CheckWeatherSG' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'CheckWeatherSGTests' do
    inherit! :complete
    # Pods for testing
  end

  use_unimodules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'CheckWeatherSG-tvOS' do
  # Pods for CheckWeatherSG-tvOS

  target 'CheckWeatherSG-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'NotificationService' do
  pod 'Firebase/Messaging'
end

target 'TodayExtension' do
  pod 'Kingfisher', '~> 5.0'
end
